version: '3'
services:
  loki:
    image: grafana/loki:2.4.0
    container_name: loki    
    ports:
      - 3100:3100
    volumes:
      - './loki:/mnt/config'
      - './loki-volumes:/etc/loki'
    command: -config.file=/mnt/config/loki-config.yml
    networks:
      - extern
      
  promtail:
    image: grafana/promtail:latest
    container_name: promtail    
    ports:
      - 1514:1514
    volumes:
      - ./promtail:/mnt/config
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/mnt/config/promtail-config.yml
    networks:
      - extern

networks:
  extern:
    external: true