global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'pi3.home:9090' 
          - 'pi3.home:9100' 
          - 'idonotexists:564'


