version: '3'

services:
  loki:
    image: grafana/loki:$LOKI_VERSION
    container_name: loki
    restart: unless-stopped
    networks: 
      - logging
      - monitoring
    ports:
      - 3100:3100
    volumes:
      - ./config-loki:/mnt/config
      - ./data:/loki
    user: 1000:1000
    command: -config.file=/mnt/config/loki-config.yml
      
  promtail:
    image: grafana/promtail:$PROMTAIL_VERSION
    container_name: promtail
    restart: unless-stopped
    networks: 
      - logging
      - monitoring
    ports:
      - 1514:1514
      - 9080:9080
    volumes:
      - ./config-promtail:/mnt/config
      - /var/log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/mnt/config/promtail-config.yml

networks:
  logging:
    name: logging
    driver: bridge
  monitoring:
    external: true
