version: '3'

services:
  prometheus:
    image: prom/prometheus:$PROMETHEUS_VERSION
    container_name: prometheus
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 9090:9090
    volumes:
      - './prometheus:/etc/prometheus'
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
    logging:
      driver: loki
      options:
        loki-url: $LOKI_URL
        no-file: "true"

  alertmanager:
    image: prom/alertmanager:$ALERTMANAGER_VESRION
    container_name: alertmanager    
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 9093:9093
    volumes:
      - "./alertmanager:/config"
      - alertmanager-data:/data
    command: --config.file=/config/alertmanager.yml --log.level=debug 
    logging:
      driver: loki
      options:
        loki-url: $LOKI_URL
        no-file: "true"

volumes:
  prometheus-data:
  alertmanager-data:

networks:
  monitoring:
    external: true