version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:$PIHOLE_VERSION
    restart: unless-stopped
    networks: 
      - default
      - reverse-proxy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: ${PIHOLE_WEBPASSWORD} 
    volumes:
      - './data/etc-pihole/:/etc/pihole/'
      - './data/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=reverse-proxy"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${DOMAIN_NAME}`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    logging:
      driver: loki
      options:
        loki-url: $LOKI_URL
        no-file: "true"

  pihole-exporter:
    container_name: pihole-exporter
    image: ekofr/pihole-exporter:latest
    restart: unless-stopped
    networks: 
      - default
      - monitoring
    ports:
      - "9617:9617/tcp"
    environment:
      PIHOLE_HOSTNAME: pihole
      PIHOLE_PASSWORD: ${PIHOLE_WEBPASSWORD}
      INTERVAL: 30s
      PORT: 9617
    logging:
      driver: loki
      options:
        loki-url: $LOKI_URL
        no-file: "true"

networks:
  default:
    driver: bridge
  reverse-proxy:
    external: true
  monitoring:
    external: true
