version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:$PIHOLE_VERSION
    restart: unless-stopped
    networks: 
      - extern
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "81:80/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: ${PH_WEBPASSWORD} 
    volumes:
      - '${HI_DATA}/pihole/etc-pihole/:/etc/pihole/'
      - '${HI_DATA}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pihole.entrypoints=https"
      - "traefik.http.routers.pihole.rule=Host(`pihole.${HI_DOMAIN_NAME}`)"
      - "traefik.http.routers.pihole.tls=true"
      - "traefik.http.routers.pihole.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #cap_add:
    #  - NET_ADMIN

networks:
  extern:
    external: true
