version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:$MOSQUITTO_VERSION
    container_name: mosquitto
    restart: unless-stopped
    volumes:
      - ./config/:/mosquitto/config/:ro
      - ./log/:/mosquitto/log/
      - mosquitto-data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
    logging:
      driver: loki
      options:
        loki-url: $LOKI_URL
        no-file: "true"

volumes:
  mosquitto-data: 