global:
  checkNewVersion: true
  sendAnonymousUsage: true

api:
  dashboard: true
  debug: true
  insecure: false

serversTransport:
  insecureSkipVerify: true

log:
  level: INFO
  format: json

accessLog:
  format: json

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    http:
      tls:
         certresolver: dns-cloudflare
         domains:
           main: "${DOMAIN_NAME}"
           sans: "*.${DOMAIN_NAME}"
 
providers:
  file:
    directory: "/fileprovider"
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: "reverse-proxy"
    exposedByDefault: false

certificatesResolvers:
  dns-cloudflare:
    acme:
      # LetsEncrypt Staging Server - uncomment when testing
      # Traefik's Default="https://acme-v02.api.letsencrypt.org/directory"
      caServer: "https://acme-v02.api.letsencrypt.org/directory" 
      email: ${CF_API_EMAIL}
      storage: "/acme.json"
      dnsChallenge:
        provider: cloudflare
        resolvers: "1.1.1.1:53,1.0.0.1:53"
        delayBeforeCheck: 90 # To delay DNS check and reduce LE hitrate