version: "3"
services:

  influxdb2:
    image: influxdb:${INFLUXDB_VERSION}
    container_name: influxdb2
    restart: unless-stopped
    networks:
      - influxdb2
    ports:
      - '8086:8086'
    volumes:
      - influxdb2-storage:/var/lib/influxdb2
      - ./config:/etc/influxdb2:rw
      - '${INFLUXDB_BACKUP_DIR}:/backup:rw'
    env_file:
      - .env
      - .secrets.env
    logging:
      driver: loki
      options:
        loki-url: $LOKI_URL
        no-file: "true"

  telegraf:
    image: telegraf:${TELEGRAF_VERSION}
    container_name: telegraf
    restart: unless-stopped
    networks:
      - influxdb2
    ports:
      - '57100:57100'
      - '57500:57500'
    env_file:
      - .env
      - .secrets.env
    volumes:
     - './telegraf:/etc/telegraf:ro'
     - '${TIBBER_SCRIPTS}:/etc/tibber/bin:rw'
     - '${TIBBER_DATA}:/etc/tibber/data:rw'
     - '/var/run/docker.sock:/var/run/docker.sock:ro'
     - '/sys:/rootfs/sys:ro'
     - '/proc:/rootfs/proc:ro'
     - '/etc:/rootfs/etc:ro'
    command: --config-directory /etc/telegraf/telegraf.d
    logging:
      driver: loki
      options:
        loki-url: $LOKI_URL
        no-file: "true"

volumes:
  influxdb2-storage:

networks:
  influxdb2:
    name: influxdb2
    driver: bridge