global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

#alerting:
#  alertmanagers:
#    - scheme: http
#      static_configs:
#        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - '192.168.1.12:9100' 
#          - '192.168.1.13:9100'
#  - job_name: 'pihole'
#    static_configs:
#      - targets: ['pihole-exporter:9617']
