version: '3'
services:
  homebridge:
    image: oznu/homebridge:$HOMEBRIDGE_VESRION
    container_name: homebridge
    restart: unless-stopped
    network_mode: host
    volumes:
      - './data:/homebridge'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homebridge.entrypoints=https"
      - "traefik.http.routers.homebridge.rule=Host(`homebridge.${DOMAIN_NAME}`)"
      - "traefik.http.routers.homebridge.tls=true"
      - "traefik.http.routers.homebridge.tls.certresolver=dns-cloudflare"
      - "traefik.http.services.homebridge.loadbalancer.server.port=8581"
      - "docker.group=homebridge"
    logging:
      driver: loki
      options:
        loki-url: $LOKI_URL
        no-file: "true"
