version: "2"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: unless-stopped
    networks: 
      - extern
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_ADMIN_ENABLED=true

  chronograf:
    image: chronograf:latest
    container_name: chronograf
    restart: unless-stopped
    networks: 
      - extern
    ports:
      - '8888:8888'
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}

  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    networks: 
      - extern
    ports:
      - '57100:57100'
      - '57500:57500'
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    volumes:
     - '${HI_DATA}/influxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
     - '${HI_DATA}/influxdb/script.sh:/etc/telegraf/script.sh:ro'
     - '${HI_DATA}/influxdb/tibber_data:/etc/tibber_data:rw'
     - '/var/run/docker.sock:/var/run/docker.sock:ro'
     - '/sys:/rootfs/sys:ro'
     - '/proc:/rootfs/proc:ro'
     - '/etc:/rootfs/etc:ro'
     
volumes:
  influxdb-storage:
  chronograf-storage:
  
networks:
  extern:
    external: true
